### ISSUE TITLE
Reply To

### ISSUE THREAD

**Issue by leandrojdl** [12-cactus/gala-estampas-web#3]
Para el form de contacto habría que probar lo siguiente:

Si se setea el campo `reply_to` con el mail del chango que está completando el formulario, cuando llega el mail a info@gala y Sil pone "Responder" tendría que setearle directamente el mail del chango. Se entiende la idea??

**Comment by sirDemian** [comment]
DONE!!! =D

Te mando un pulreke para cuando puedas...
