### ISSUE TITLE
Galería en Promociones

### ISSUE THREAD

**Issue by laendoor** [12-cactus/gala-estampas-web#5]
Quedaría bueno que en Promociones se puedan ver los productos como una galería, donde las imágenes se vean más grandes y se vayan pasando con flechitas (tipo como lo ves en face) o algo por el estilo.

Te dejo investigar y cualquier cosa avisame y vemos opciones juntos si nada te convence.

**Comment by sirDemian** [comment]
ok, tipo una calesita o ruleta no recuerdo el nombre. Ahora la pregunta sería: no quedaría mejor que este en la onepage en vez de abrir una ventana nueva?
Pregunto desde el diseño, lo puedo hacer "ahora" en esa pagina nueva y de última desp la cambio de lugar

**Comment by laendoor** [comment]
Yo decía algo tipo Modal. Los Modales son esas subventanas que solo ocupan una parte de la pantalla y se posicionan encima de lo que está, tipo como cuando ves fotos en facebook.

Igual es una idea nomás.

**Comment by sirDemian** [comment]
DONE!!!
