### ISSUE TITLE
[Sugerencia] Texto en Promociones

### ISSUE THREAD

**Issue by laendoor** [12-cactus/gala-estampas-web#6]
(Esto es solo una sugerencia)

Hay algo que suena mal en "Empiezan las clases y nuestros más peques se merecen un hermoso set personalizado para iniciar el jardín."

Yo le cambiaría el "nuestros más peques" por:

1) "nuestros peques"
2) "lo más peques"

Tampoco me gusta como suena "iniciar", quizás podría ser "comenzar" o "empezar", pero no sé.

**Comment by sirDemian** [comment]
No a lugar.... pongo texto para no poner lorem ipsum.... lo mismo q la promo de los set no es lo que me interesa en sí, sino que este la estructura para que se vea la promo q va a estar vigente. Llegado el momento Sil me dirá q texto y que promo irá...
